import { ROOM_TYPES } from './config/RoomTypes.js';

const MOCK_FILES_BY_TYPE = {
  forge: {
    'main.py':       "from flask import Flask\napp = Flask(__name__)\n\n@app.route('/')\ndef index():\n    return 'hello'\n",
    'package.json':  '{ "name": "forge-task", "version": "0.1.0" }\n',
    'README.md':     '# Forge Task\nGenerated by an agent session.\n',
  },
  warroom: {
    'stacktrace.log': 'TypeError: cannot read property "x" of undefined\n  at handler (server.js:42)\n  at process (server.js:18)\n',
    'server.js':      'function handler(req) {\n  return req.body.x.toString();\n}\n',
    'fix.patch':      '--- a/server.js\n+++ b/server.js\n@@\n-  return req.body.x.toString();\n+  return (req.body?.x ?? "").toString();\n',
  },
  blueprint: {
    'schema.sql':       'CREATE TABLE users (\n  id SERIAL PRIMARY KEY,\n  email TEXT UNIQUE,\n  created_at TIMESTAMP\n);\n',
    'architecture.md':  '# Architecture\n- API layer: Express\n- DB: Postgres\n- Cache: Redis\n',
    'prompts.md':       '# Agent prompts\n1. Refine schema\n2. Generate queries\n',
  },
  lounge: {
    'README.md':     "# Welcome\nA cozy place to write docs.\n",
    'CHANGELOG.md':  '## 0.1.0\n- Initial release\n',
    'docs/intro.md': '# Intro\nThis project is...\n',
  },
};

const MOCK_AGENT_LINES = {
  forge: [
    'scaffolding component tree...',
    "wrote handlers in src/api/route.js",
    'wiring state into store...',
    'ran tests — all green',
  ],
  warroom: [
    'reproduced the crash locally',
    'isolated null pointer in handler()',
    'patch staged, running regression suite',
    'fix verified — no more 500s',
  ],
  blueprint: [
    'sketching entity relationships...',
    'normalized users + sessions tables',
    'drafted index plan',
    'shipping schema.sql for review',
  ],
  lounge: [
    'pulling existing copy...',
    'restructured intro for clarity',
    'added a quickstart section',
    'doc lint pass — clean',
  ],
};

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

class TaskSpawner {
  constructor() {
    this.btn = document.getElementById('new-task-btn');
    this.modal = document.getElementById('new-task-modal');
    this.input = document.getElementById('new-task-input');
    this.cancel = document.getElementById('new-task-cancel');
    this.form = this.modal.querySelector('form');

    this.btn.addEventListener('click', () => this.open());
    this.cancel.addEventListener('click', () => this.close());
    this.modal.addEventListener('click', (e) => {
      if (e.target === this.modal) this.close();
    });
    this.form.addEventListener('submit', (e) => {
      e.preventDefault();
      const v = this.input.value.trim();
      if (!v) return;
      window.dispatchEvent(new CustomEvent('agentoffice:new-task', { detail: { prompt: v } }));
      this.input.value = '';
      this.close();
    });
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && this.modal.getAttribute('aria-hidden') === 'false') {
        this.close();
      }
    });
  }

  open() {
    this.modal.setAttribute('aria-hidden', 'false');
    setTimeout(() => this.input.focus(), 50);
  }

  close() {
    this.modal.setAttribute('aria-hidden', 'true');
  }
}

class TerminalUI {
  constructor() {
    this.panel = document.getElementById('terminal-panel');
    this.log = this.panel.querySelector('[data-bind="log"]');
    this.titleEl = this.panel.querySelector('[data-bind="roomLabel"]');
    this.input = document.getElementById('terminal-input');
    this.closeBtn = document.getElementById('terminal-close');
    this.form = this.panel.querySelector('.terminal-form');

    this.activeRoom = null;
    this.logsByRoom = new Map();
    this.fsByRoom = new Map();

    this.closeBtn.addEventListener('click', () => this.close());
    this.form.addEventListener('submit', (e) => {
      e.preventDefault();
      const v = this.input.value;
      if (!v.trim()) return;
      this.handleInput(v);
      this.input.value = '';
    });
    window.addEventListener('agentoffice:room-selected', (e) => this.open(e.detail));
  }

  open(payload) {
    this.activeRoom = payload;
    this.titleEl.textContent = `${payload.label} · ${payload.roomId}`;
    this.panel.setAttribute('aria-hidden', 'false');
    this.panel.classList.add('open');

    if (!this.logsByRoom.has(payload.roomId)) {
      this.logsByRoom.set(payload.roomId, []);
      this.fsByRoom.set(payload.roomId, { ...(MOCK_FILES_BY_TYPE[payload.roomType] ?? {}) });
      this.appendLine('agent', `[${payload.label}] session attached — ${ROOM_TYPES[payload.roomType]?.ambient ?? ''}`);
      if (payload.prompt) {
        this.appendLine('user', payload.prompt);
        this.streamAgentReply(payload);
      }
    }
    this.renderLogs();
    setTimeout(() => this.input.focus(), 50);
  }

  close() {
    this.panel.setAttribute('aria-hidden', 'true');
    this.panel.classList.remove('open');
    this.activeRoom = null;
  }

  handleInput(raw) {
    if (!this.activeRoom) return;
    if (raw.startsWith('! ')) {
      const cmd = raw.slice(2).trim();
      this.appendLine('user', raw);
      this.runShell(cmd);
    } else if (raw === '!') {
      this.appendLine('shell', "usage: ! ls   |   ! cat <file>");
    } else {
      this.appendLine('user', raw);
      this.streamAgentReply({ ...this.activeRoom, prompt: raw });
    }
  }

  runShell(cmd) {
    const fs = this.fsByRoom.get(this.activeRoom.roomId) ?? {};
    if (cmd === 'ls') {
      const files = Object.keys(fs);
      this.appendLine('shell', files.length ? files.join('\n') : '(empty workspace)');
      return;
    }
    if (cmd.startsWith('cat ')) {
      const name = cmd.slice(4).trim();
      if (fs[name] != null) {
        this.appendLine('shell', fs[name]);
      } else {
        this.appendLine('error', `cat: ${name}: no such file`);
      }
      return;
    }
    if (cmd === 'pwd') {
      this.appendLine('shell', `./workspace/${this.activeRoom.roomId}/`);
      return;
    }
    if (cmd === 'help') {
      this.appendLine('shell', 'available: ls | cat <file> | pwd | help');
      return;
    }
    this.appendLine('error', `${cmd}: command not found (try: help)`);
  }

  streamAgentReply(payload) {
    const lines = MOCK_AGENT_LINES[payload.roomType] ?? MOCK_AGENT_LINES.forge;
    const line = pickRandom(lines);
    const el = document.createElement('span');
    el.className = 'line line-agent';
    el.textContent = '· ';
    this.log.appendChild(el);
    let i = 0;
    const tick = () => {
      if (i >= line.length) { this.scrollLog(); return; }
      el.textContent = '· ' + line.slice(0, ++i);
      this.scrollLog();
      setTimeout(tick, 14);
    };
    tick();
  }

  appendLine(kind, text) {
    const log = this.logsByRoom.get(this.activeRoom.roomId);
    log.push({ kind, text });
    const el = document.createElement('span');
    el.className = `line line-${kind}`;
    el.textContent =
      kind === 'user'  ? `> ${text}` :
      kind === 'agent' ? `· ${text}` :
      text;
    this.log.appendChild(el);
    this.scrollLog();
    return el;
  }

  renderLogs() {
    this.log.innerHTML = '';
    const log = this.logsByRoom.get(this.activeRoom.roomId) ?? [];
    for (const entry of log) {
      const el = document.createElement('span');
      el.className = `line line-${entry.kind}`;
      el.textContent =
        entry.kind === 'user'  ? `> ${entry.text}` :
        entry.kind === 'agent' ? `· ${entry.text}` :
        entry.text;
      this.log.appendChild(el);
    }
    this.scrollLog();
  }

  scrollLog() {
    this.log.scrollTop = this.log.scrollHeight;
  }
}

// Emojis live only as comments in RoomLayouts; map them here so the task list
// gets visual glyphs without touching world/ or config/ owned by other agents.
const ROOM_TYPE_EMOJI = {
  forge:     '🏭',
  warroom:   '🚨',
  blueprint: '📐',
  lounge:    '📚',
};

const INTEGRATIONS = [
  { id: 'linear',  name: 'Linear',         color: '#5E6AD2' },
  { id: 'trello',  name: 'Trello',         color: '#0079BF' },
  { id: 'jira',    name: 'Jira',           color: '#2684FF' },
  { id: 'github',  name: 'GitHub Issues',  color: '#c9d1d9' },
  { id: 'asana',   name: 'Asana',          color: '#F06A6A' },
  { id: 'notion',  name: 'Notion',         color: '#e6e6e6' },
];

function emptyStateHTML() {
  const buttons = INTEGRATIONS.map(svc => `
      <button class="integration-btn" type="button" data-svc="${svc.id}">
        <span class="integration-dot" style="--svc:${svc.color}"></span>
        <span class="integration-name">${svc.name}</span>
        <span class="integration-arrow">›</span>
      </button>`).join('');
  return `
    <p class="empty-msg">no sessions yet — spawn one with + New Task</p>
    <div class="empty-divider"><span>or connect</span></div>
    <div class="integration-list">${buttons}</div>
  `;
}

// 0xRRGGBB int -> css hex (RoomTypes.tint is a Phaser-friendly integer)
function tintToCss(tint) {
  return '#' + (tint ?? 0xffffff).toString(16).padStart(6, '0');
}

class TaskListUI {
  constructor() {
    this.panel = document.getElementById('task-list-panel');
    this.itemsEl = this.panel.querySelector('[data-bind="items"]');
    this.countEl = this.panel.querySelector('[data-bind="count"]');
    this.toggleBtn = this.panel.querySelector('.task-list-toggle');
    this.activeRoomId = null;
    // Track last-rendered signature so we only rebuild the DOM on real changes.
    this.lastSig = '';

    if (localStorage.getItem('agentoffice:tasks-collapsed') === '1') {
      this.setCollapsed(true);
    }
    this.toggleBtn?.addEventListener('click', () => {
      this.setCollapsed(!this.panel.classList.contains('collapsed'));
    });

    window.addEventListener('agentoffice:room-selected', (e) => {
      this.activeRoomId = e.detail?.roomId ?? null;
      this.refresh();
    });

    // Poll the scene — simpler than threading new events through the scene
    // and cheap enough at 500ms with O(rooms) work.
    setInterval(() => this.refresh(), 500);
  }

  setCollapsed(collapsed) {
    this.panel.classList.toggle('collapsed', collapsed);
    this.toggleBtn?.setAttribute('aria-expanded', String(!collapsed));
    localStorage.setItem('agentoffice:tasks-collapsed', collapsed ? '1' : '0');
  }

  _getRooms() {
    const scene = window.__agentoffice?.game?.scene?.getScene?.('AgencyFloorScene');
    return scene?.rooms ?? [];
  }

  refresh() {
    const rooms = this._getRooms();
    // Signature includes anything that affects render: id, prompt, state, active.
    const sig = rooms
      .map(r => `${r.roomId}|${r.roomType}|${r.prompt}|${r.agent?.agentState ?? ''}|${r.roomId === this.activeRoomId ? 1 : 0}`)
      .join('::');
    if (sig === this.lastSig) return;
    this.lastSig = sig;
    this.render(rooms);
  }

  render(rooms) {
    this.countEl.textContent = String(rooms.length);
    if (rooms.length === 0) {
      this.itemsEl.innerHTML = `<div class="task-list-empty">${emptyStateHTML()}</div>`;
      return;
    }
    this.itemsEl.innerHTML = '';
    for (const room of rooms) {
      const meta = ROOM_TYPES[room.roomType] ?? ROOM_TYPES.forge;
      const tintCss = tintToCss(meta.tint);
      const state = room.agent?.agentState ?? 'idle';

      const card = document.createElement('div');
      card.className = 'task-card' + (room.roomId === this.activeRoomId ? ' active' : '');
      card.dataset.roomId = room.roomId;
      card.style.borderLeftColor = tintCss;

      const head = document.createElement('div');
      head.className = 'task-card-head';

      const icon = document.createElement('span');
      icon.className = 'task-card-icon';
      icon.textContent = ROOM_TYPE_EMOJI[room.roomType] ?? '•';
      head.appendChild(icon);

      const label = document.createElement('span');
      label.className = 'task-card-label';
      label.style.color = tintCss;
      label.textContent = meta.label;
      head.appendChild(label);

      const prompt = document.createElement('div');
      prompt.className = 'task-card-prompt';
      prompt.textContent = room.prompt ?? '(no prompt)';

      const stateEl = document.createElement('div');
      stateEl.className = 'task-card-state';
      stateEl.dataset.state = state;
      const dot = document.createElement('span');
      dot.className = 'task-card-state-dot';
      stateEl.appendChild(dot);
      const stateText = document.createElement('span');
      stateText.textContent = state;
      stateEl.appendChild(stateText);

      card.appendChild(head);
      card.appendChild(prompt);
      card.appendChild(stateEl);

      card.addEventListener('click', () => this._select(room.roomId));
      this.itemsEl.appendChild(card);
    }
  }

  _select(roomId) {
    const scene = window.__agentoffice?.game?.scene?.getScene?.('AgencyFloorScene');
    scene?.openTerminalForRoom?.(roomId);
  }
}

function gatePhaserKeyboard() {
  const game = window.__agentoffice?.game;
  if (!game?.input?.keyboard) return;
  const el = document.activeElement;
  const typing =
    !!el &&
    (el.tagName === 'INPUT' ||
      el.tagName === 'TEXTAREA' ||
      el.isContentEditable);
  game.input.keyboard.enabled = !typing;
}

export function initUI() {
  new TaskSpawner();
  new TerminalUI();
  new TaskListUI();
  document.addEventListener('focusin', gatePhaserKeyboard);
  document.addEventListener('focusout', gatePhaserKeyboard);
}
