import { ROOM_TYPES } from './config/RoomTypes.js';
import { backend } from './backend.js';
import { describeHits, queryGBrain, rememberGBrain } from './gbrain.js';

const MOCK_FILES_BY_TYPE = {
  forge: {
    'main.py':       "from flask import Flask\napp = Flask(__name__)\n\n@app.route('/')\ndef index():\n    return 'hello'\n",
    'package.json':  '{ "name": "forge-task", "version": "0.1.0" }\n',
    'README.md':     '# Forge Task\nGenerated by an agent session.\n',
  },
  warroom: {
    'stacktrace.log': 'TypeError: cannot read property "x" of undefined\n  at handler (server.js:42)\n  at process (server.js:18)\n',
    'server.js':      'function handler(req) {\n  return req.body.x.toString();\n}\n',
    'fix.patch':      '--- a/server.js\n+++ b/server.js\n@@\n-  return req.body.x.toString();\n+  return (req.body?.x ?? "").toString();\n',
  },
  blueprint: {
    'schema.sql':       'CREATE TABLE users (\n  id SERIAL PRIMARY KEY,\n  email TEXT UNIQUE,\n  created_at TIMESTAMP\n);\n',
    'architecture.md':  '# Architecture\n- API layer: Express\n- DB: Postgres\n- Cache: Redis\n',
    'prompts.md':       '# Agent prompts\n1. Refine schema\n2. Generate queries\n',
  },
  lounge: {
    'README.md':     "# Welcome\nA cozy place to write docs.\n",
    'CHANGELOG.md':  '## 0.1.0\n- Initial release\n',
    'docs/intro.md': '# Intro\nThis project is...\n',
  },
};

const MOCK_AGENT_LINES = {
  forge: [
    'scaffolding component tree...',
    "wrote handlers in src/api/route.js",
    'wiring state into store...',
    'ran tests — all green',
  ],
  warroom: [
    'reproduced the crash locally',
    'isolated null pointer in handler()',
    'patch staged, running regression suite',
    'fix verified — no more 500s',
  ],
  blueprint: [
    'sketching entity relationships...',
    'normalized users + sessions tables',
    'drafted index plan',
    'shipping schema.sql for review',
  ],
  lounge: [
    'pulling existing copy...',
    'restructured intro for clarity',
    'added a quickstart section',
    'doc lint pass — clean',
  ],
};

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

class TaskSpawner {
  constructor() {
    this.btn = document.getElementById('new-task-btn');
    this.modal = document.getElementById('new-task-modal');
    this.input = document.getElementById('new-task-input');
    this.cancel = document.getElementById('new-task-cancel');
    this.form = this.modal.querySelector('form');

    this.btn.addEventListener('click', () => this.open());
    this.cancel.addEventListener('click', () => this.close());
    this.modal.addEventListener('click', (e) => {
      if (e.target === this.modal) this.close();
    });
    this.form.addEventListener('submit', (e) => {
      e.preventDefault();
      const v = this.input.value.trim();
      if (!v) return;
      window.dispatchEvent(new CustomEvent('agentoffice:new-task', { detail: { prompt: v } }));
      this.input.value = '';
      this.close();
    });
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && this.modal.getAttribute('aria-hidden') === 'false') {
        this.close();
      }
    });
  }

  open() {
    this.modal.setAttribute('aria-hidden', 'false');
    setTimeout(() => this.input.focus(), 50);
  }

  close() {
    this.modal.setAttribute('aria-hidden', 'true');
  }
}

class TerminalUI {
  constructor() {
    this.panel = document.getElementById('terminal-panel');
    this.log = this.panel.querySelector('[data-bind="log"]');
    this.titleEl = this.panel.querySelector('[data-bind="roomLabel"]');
    this.input = document.getElementById('terminal-input');
    this.closeBtn = document.getElementById('terminal-close');
    this.form = this.panel.querySelector('.terminal-form');

    this.activeRoom = null;
    this.logsByRoom = new Map();
    this.fsByRoom = new Map();

    this.closeBtn.addEventListener('click', () => this.close());
    this.form.addEventListener('submit', (e) => {
      e.preventDefault();
      const v = this.input.value;
      if (!v.trim()) return;
      this.handleInput(v);
      this.input.value = '';
    });
    window.addEventListener('agentoffice:room-selected', (e) => this.open(e.detail));

    // Backend terminal output stream
    window.addEventListener('backend:terminal:output', (e) => {
      const { roomId, kind, text } = e.detail ?? {};
      if (!roomId || !text) return;

      // Store in local log buffer
      if (!this.logsByRoom.has(roomId)) this.logsByRoom.set(roomId, []);
      this.logsByRoom.get(roomId).push({ kind, text });

      // Render if this room's terminal is active
      if (this.activeRoom?.roomId === roomId) {
        const el = document.createElement('span');
        el.className = `line line-${kind}`;
        el.textContent = kind === 'agent' ? `· ${text}` : text;
        this.log.appendChild(el);
        this.scrollLog();
      }
    });
  }

  open(payload) {
    this.activeRoom = payload;
    this.titleEl.textContent = `${payload.label} · ${payload.roomId}`;
    this.panel.setAttribute('aria-hidden', 'false');
    this.panel.classList.add('open');

    if (!this.logsByRoom.has(payload.roomId)) {
      this.logsByRoom.set(payload.roomId, []);
      this.fsByRoom.set(payload.roomId, { ...(MOCK_FILES_BY_TYPE[payload.roomType] ?? {}) });
      this.appendLine('agent', `[${payload.label}] session attached — ${ROOM_TYPES[payload.roomType]?.ambient ?? ''}`);
      if (payload.prompt) {
        this.appendLine('user', payload.prompt);
        void this.streamAgentReply(payload);
      }
    }
    this.renderLogs();
    setTimeout(() => this.input.focus(), 50);
  }

  close() {
    this.panel.setAttribute('aria-hidden', 'true');
    this.panel.classList.remove('open');
    this.activeRoom = null;
  }

  handleInput(raw) {
    if (!this.activeRoom) return;

    // Route through backend when connected
    if (backend.connected) {
      this.appendLine('user', raw);
      backend.send('terminal:input', {
        roomId: this.activeRoom.roomId,
        input: raw,
      });
      return;
    }

    // Fallback: local mock
    if (raw.startsWith('! ')) {
      const cmd = raw.slice(2).trim();
      this.appendLine('user', raw);
      this.runShell(cmd);
    } else if (raw === '!') {
      this.appendLine('shell', "usage: ! ls   |   ! cat <file>");
    } else {
      this.appendLine('user', raw);
      void this.streamAgentReply({ ...this.activeRoom, prompt: raw });
    }
  }

  runShell(cmd) {
    const fs = this.fsByRoom.get(this.activeRoom.roomId) ?? {};
    if (cmd === 'ls') {
      const files = Object.keys(fs);
      this.appendLine('shell', files.length ? files.join('\n') : '(empty workspace)');
      return;
    }
    if (cmd.startsWith('cat ')) {
      const name = cmd.slice(4).trim();
      if (fs[name] != null) {
        this.appendLine('shell', fs[name]);
      } else {
        this.appendLine('error', `cat: ${name}: no such file`);
      }
      return;
    }
    if (cmd === 'pwd') {
      this.appendLine('shell', `./workspace/${this.activeRoom.roomId}/`);
      return;
    }
    if (cmd === 'help') {
      this.appendLine('shell', 'available: ls | cat <file> | pwd | help');
      return;
    }
    this.appendLine('error', `${cmd}: command not found (try: help)`);
  }

  async streamAgentReply(payload) {
    // Real backend path streams agent output via backend:terminal:output
    // already, so don't double-emit mock content.
    if (backend.connected) return;

    try {
      const { source, hits } = await queryGBrain(payload.prompt ?? '');
      this.appendLine('agent', `[g-brain] ${describeHits(hits)}${source === 'server' ? ' (server)' : ''}`);
    } catch {
      // Memory lookup is best-effort; continue with the mock reply.
    }

    const lines = MOCK_AGENT_LINES[payload.roomType] ?? MOCK_AGENT_LINES.forge;
    const line = pickRandom(lines);
    const el = document.createElement('span');
    el.className = 'line line-agent';
    el.textContent = '· ';
    this.log.appendChild(el);
    let i = 0;
    const tick = () => {
      if (i >= line.length) {
        this.scrollLog();
        void rememberGBrain({
          sourceSessionId: payload.roomId,
          title: payload.prompt ?? payload.roomId,
          text: `${payload.prompt ?? ''}\n${line}`,
        });
        return;
      }
      el.textContent = '· ' + line.slice(0, ++i);
      this.scrollLog();
      setTimeout(tick, 14);
    };
    tick();
  }

  appendLine(kind, text) {
    const log = this.logsByRoom.get(this.activeRoom.roomId);
    log.push({ kind, text });
    const el = document.createElement('span');
    el.className = `line line-${kind}`;
    el.textContent =
      kind === 'user'  ? `> ${text}` :
      kind === 'agent' ? `· ${text}` :
      text;
    this.log.appendChild(el);
    this.scrollLog();
    return el;
  }

  renderLogs() {
    this.log.innerHTML = '';
    const log = this.logsByRoom.get(this.activeRoom.roomId) ?? [];
    for (const entry of log) {
      const el = document.createElement('span');
      el.className = `line line-${entry.kind}`;
      el.textContent =
        entry.kind === 'user'  ? `> ${entry.text}` :
        entry.kind === 'agent' ? `· ${entry.text}` :
        entry.text;
      this.log.appendChild(el);
    }
    this.scrollLog();
  }

  scrollLog() {
    this.log.scrollTop = this.log.scrollHeight;
  }
}

// Emojis live only as comments in RoomLayouts; map them here so the task list
// gets visual glyphs without touching world/ or config/ owned by other agents.
const ROOM_TYPE_EMOJI = {
  forge:     '🏭',
  warroom:   '🚨',
  blueprint: '📐',
  lounge:    '📚',
};

const INTEGRATIONS = [
  { id: 'linear',  name: 'Linear',         color: '#5E6AD2' },
  { id: 'trello',  name: 'Trello',         color: '#0079BF' },
  { id: 'jira',    name: 'Jira',           color: '#2684FF' },
  { id: 'github',  name: 'GitHub Issues',  color: '#c9d1d9' },
  { id: 'asana',   name: 'Asana',          color: '#F06A6A' },
  { id: 'notion',  name: 'Notion',         color: '#e6e6e6' },
];

function emptyStateHTML() {
  const buttons = INTEGRATIONS.map(svc => `
      <button class="integration-btn" type="button" data-svc="${svc.id}">
        <span class="integration-dot" style="--svc:${svc.color}"></span>
        <span class="integration-name">${svc.name}</span>
        <span class="integration-arrow">›</span>
      </button>`).join('');
  return `
    <p class="empty-msg">no sessions yet — spawn one with + New Task</p>
    <div class="empty-divider"><span>or connect</span></div>
    <div class="integration-list">${buttons}</div>
  `;
}

// 0xRRGGBB int -> css hex (RoomTypes.tint is a Phaser-friendly integer)
function tintToCss(tint) {
  return '#' + (tint ?? 0xffffff).toString(16).padStart(6, '0');
}

const KANBAN_COLUMNS = [
  { id: 'todo', label: 'Todo' },
  { id: 'doing', label: 'In Progress' },
  { id: 'review', label: 'Review' },
  { id: 'done', label: 'Done' },
  { id: 'blocked', label: 'Blocked' },
];

// Map agent state to kanban column for rooms without a Linear workflow state.
function columnFromAgentState(state) {
  if (state === 'success' || state === 'done' || state === 'dormant') return 'done';
  if (state === 'error') return 'blocked';
  if (state === 'thinking') return 'review';
  if (state === 'typing' || state === 'executing' || state === 'walking') return 'doing';
  return 'todo';
}

// Linear workflow state -> kanban column. Loose match so custom workspaces
// with slightly different names (e.g. "In review", "in-progress") still land.
function columnFromLinearState(state) {
  const s = String(state).toLowerCase();
  if (s.includes('review'))                 return 'review';
  if (s.includes('progress') || s.includes('doing')) return 'doing';
  if (s.includes('done') || s.includes('cancel')) return 'done';
  if (s.includes('block')) return 'blocked';
  if (s.includes('todo') || s.includes('backlog') || s.includes('open')) return 'todo';
  return null;
}

function columnForRoom(room) {
  const agentState = room.agent?.agentState ?? 'idle';
  // Errors take precedence — a failed run is blocked regardless of Linear state.
  if (agentState === 'error') return 'blocked';

  const linearCol = room.linearState ? columnFromLinearState(room.linearState) : null;
  if (linearCol) return linearCol;

  return columnFromAgentState(agentState);
}

function statusTextForRoom(room) {
  const agentState = room.agent?.agentState ?? 'idle';
  if (room.linearState) {
    return `${room.linearState.toLowerCase()} · ${agentState}`;
  }
  return agentState;
}

class TaskListUI {
  constructor() {
    this.panel = document.getElementById('task-list-panel');
    this.itemsEl = this.panel.querySelector('[data-bind="items"]');
    this.countEl = this.panel.querySelector('[data-bind="count"]');
    this.toggleBtn = this.panel.querySelector('.task-list-toggle');
    this.headerEl = this.panel.querySelector('.task-list-header');
    this.activeRoomId = null;
    this.viewMode = localStorage.getItem('agentoffice:task-view') || 'sessions';
    // Track last-rendered signature so we only rebuild the DOM on real changes.
    this.lastSig = '';

    this.tabsEl = document.createElement('div');
    this.tabsEl.className = 'task-list-tabs';
    this.tabsEl.innerHTML = `
      <button class="task-list-tab" type="button" data-view="sessions">Sessions</button>
      <button class="task-list-tab" type="button" data-view="kanban">Kanban</button>
    `;
    this.headerEl.after(this.tabsEl);

    if (localStorage.getItem('agentoffice:tasks-collapsed') === '1') {
      this.setCollapsed(true);
    }
    this.setView(this.viewMode, { persist: false });
    this.toggleBtn?.addEventListener('click', () => {
      this.setCollapsed(!this.panel.classList.contains('collapsed'));
    });
    this.tabsEl.addEventListener('click', (e) => {
      const btn = e.target.closest('[data-view]');
      if (!btn) return;
      this.setView(btn.dataset.view);
    });

    window.addEventListener('agentoffice:room-selected', (e) => {
      this.activeRoomId = e.detail?.roomId ?? null;
      this.refresh();
    });

    // Poll the scene — simpler than threading new events through the scene
    // and cheap enough at 500ms with O(rooms) work.
    setInterval(() => this.refresh(), 500);
  }

  setCollapsed(collapsed) {
    this.panel.classList.toggle('collapsed', collapsed);
    this.toggleBtn?.setAttribute('aria-expanded', String(!collapsed));
    localStorage.setItem('agentoffice:tasks-collapsed', collapsed ? '1' : '0');
  }

  setView(view, { persist = true } = {}) {
    this.viewMode = view === 'kanban' ? 'kanban' : 'sessions';
    for (const btn of this.tabsEl.querySelectorAll('[data-view]')) {
      btn.classList.toggle('active', btn.dataset.view === this.viewMode);
    }
    if (persist) localStorage.setItem('agentoffice:task-view', this.viewMode);
    this.refresh(true);
  }

  _getRooms() {
    const scene = window.__agentoffice?.game?.scene?.getScene?.('AgencyFloorScene');
    return scene?.rooms ?? [];
  }

  refresh(force = false) {
    const rooms = this._getRooms();
    // Signature includes anything that affects render: id, prompt, state, linear state, active.
    const sig = rooms
      .map(r => `${r.roomId}|${r.roomType}|${r.prompt}|${r.linearState ?? ''}|${r.agent?.agentState ?? ''}|${r.roomId === this.activeRoomId ? 1 : 0}`)
      .join('::') + '##' + this.viewMode;
    if (!force && sig === this.lastSig) return;
    this.lastSig = sig;
    this.render(rooms);
  }

  render(rooms) {
    this.countEl.textContent = String(rooms.length);
    if (this.viewMode === 'kanban') {
      this.renderKanban(rooms);
      return;
    }
    this.renderSessions(rooms);
  }

  renderSessions(rooms) {
    if (rooms.length === 0) {
      this.itemsEl.innerHTML = `<div class="task-list-empty">${emptyStateHTML()}</div>`;
      return;
    }
    this.itemsEl.innerHTML = '';
    for (const room of rooms) {
      const meta = ROOM_TYPES[room.roomType] ?? ROOM_TYPES.forge;
      const tintCss = tintToCss(meta.tint);
      const state = room.agent?.agentState ?? 'idle';
      const status = statusTextForRoom(room);

      const card = document.createElement('div');
      card.className = 'task-card' + (room.roomId === this.activeRoomId ? ' active' : '');
      card.dataset.roomId = room.roomId;
      card.style.borderLeftColor = tintCss;

      const head = document.createElement('div');
      head.className = 'task-card-head';

      const icon = document.createElement('span');
      icon.className = 'task-card-icon';
      icon.textContent = ROOM_TYPE_EMOJI[room.roomType] ?? '•';
      head.appendChild(icon);

      const label = document.createElement('span');
      label.className = 'task-card-label';
      label.style.color = tintCss;
      label.textContent = meta.label;
      head.appendChild(label);

      if (room.linearIdentifier) {
        const linId = document.createElement('span');
        linId.className = 'task-card-linear';
        linId.textContent = room.linearIdentifier;
        head.appendChild(linId);
      }

      const prompt = document.createElement('div');
      prompt.className = 'task-card-prompt';
      prompt.textContent = room.prompt ?? '(no prompt)';

      const stateEl = document.createElement('div');
      stateEl.className = 'task-card-state';
      stateEl.dataset.state = state;
      const dot = document.createElement('span');
      dot.className = 'task-card-state-dot';
      stateEl.appendChild(dot);
      const stateText = document.createElement('span');
      stateText.textContent = status;
      stateEl.appendChild(stateText);

      card.appendChild(head);
      card.appendChild(prompt);
      card.appendChild(stateEl);

      card.addEventListener('click', () => this._select(room.roomId));
      this.itemsEl.appendChild(card);
    }
  }

  renderKanban(rooms) {
    this.itemsEl.innerHTML = '';

    if (rooms.length === 0) {
      this.itemsEl.innerHTML = `<div class="task-list-empty">${emptyStateHTML()}</div>`;
      return;
    }

    const board = document.createElement('div');
    board.className = 'kanban-board';

    for (const column of KANBAN_COLUMNS) {
      const colEl = document.createElement('section');
      colEl.className = 'kanban-column';
      colEl.dataset.column = column.id;

      const colRooms = rooms.filter((room) => columnForRoom(room) === column.id);
      const header = document.createElement('header');
      header.className = 'kanban-column-header';
      header.innerHTML = `<span>${column.label}</span><span>${colRooms.length}</span>`;
      colEl.appendChild(header);

      const body = document.createElement('div');
      body.className = 'kanban-column-body';
      if (!colRooms.length) {
        const empty = document.createElement('div');
        empty.className = 'kanban-empty';
        empty.textContent = 'empty';
        body.appendChild(empty);
      }

      for (const room of colRooms) {
        const meta = ROOM_TYPES[room.roomType] ?? ROOM_TYPES.forge;
        const card = document.createElement('button');
        card.type = 'button';
        card.className = 'kanban-card' + (room.roomId === this.activeRoomId ? ' active' : '');
        card.addEventListener('click', () => this._select(room.roomId));

        const title = document.createElement('span');
        title.className = 'kanban-card-title';
        title.textContent = room.prompt ?? '(no prompt)';
        card.appendChild(title);

        const cardMeta = document.createElement('span');
        cardMeta.className = 'kanban-card-meta';
        const idLabel = room.linearIdentifier ? `${room.linearIdentifier} · ` : '';
        cardMeta.textContent = `${idLabel}${meta.label}`;
        card.appendChild(cardMeta);

        const state = document.createElement('span');
        state.className = 'kanban-card-state';
        state.textContent = statusTextForRoom(room);
        card.appendChild(state);

        body.appendChild(card);
      }

      colEl.appendChild(body);
      board.appendChild(colEl);
    }

    this.itemsEl.appendChild(board);
  }

  _select(roomId) {
    const scene = window.__agentoffice?.game?.scene?.getScene?.('AgencyFloorScene');
    scene?.openTerminalForRoom?.(roomId);
  }
}

function gatePhaserKeyboard() {
  const game = window.__agentoffice?.game;
  if (!game?.input?.keyboard) return;
  const el = document.activeElement;
  const typing =
    !!el &&
    (el.tagName === 'INPUT' ||
      el.tagName === 'TEXTAREA' ||
      el.isContentEditable);
  game.input.keyboard.enabled = !typing;
}

export function initUI() {
  new TaskSpawner();
  new TerminalUI();
  new TaskListUI();
  document.addEventListener('focusin', gatePhaserKeyboard);
  document.addEventListener('focusout', gatePhaserKeyboard);
}
