import { ROOM_TYPES } from './config/RoomTypes.js';

const MOCK_FILES_BY_TYPE = {
  forge: {
    'main.py':       "from flask import Flask\napp = Flask(__name__)\n\n@app.route('/')\ndef index():\n    return 'hello'\n",
    'package.json':  '{ "name": "forge-task", "version": "0.1.0" }\n',
    'README.md':     '# Forge Task\nGenerated by an agent session.\n',
  },
  warroom: {
    'stacktrace.log': 'TypeError: cannot read property "x" of undefined\n  at handler (server.js:42)\n  at process (server.js:18)\n',
    'server.js':      'function handler(req) {\n  return req.body.x.toString();\n}\n',
    'fix.patch':      '--- a/server.js\n+++ b/server.js\n@@\n-  return req.body.x.toString();\n+  return (req.body?.x ?? "").toString();\n',
  },
  blueprint: {
    'schema.sql':       'CREATE TABLE users (\n  id SERIAL PRIMARY KEY,\n  email TEXT UNIQUE,\n  created_at TIMESTAMP\n);\n',
    'architecture.md':  '# Architecture\n- API layer: Express\n- DB: Postgres\n- Cache: Redis\n',
    'prompts.md':       '# Agent prompts\n1. Refine schema\n2. Generate queries\n',
  },
  lounge: {
    'README.md':     "# Welcome\nA cozy place to write docs.\n",
    'CHANGELOG.md':  '## 0.1.0\n- Initial release\n',
    'docs/intro.md': '# Intro\nThis project is...\n',
  },
};

const MOCK_AGENT_LINES = {
  forge: [
    'scaffolding component tree...',
    "wrote handlers in src/api/route.js",
    'wiring state into store...',
    'ran tests — all green',
  ],
  warroom: [
    'reproduced the crash locally',
    'isolated null pointer in handler()',
    'patch staged, running regression suite',
    'fix verified — no more 500s',
  ],
  blueprint: [
    'sketching entity relationships...',
    'normalized users + sessions tables',
    'drafted index plan',
    'shipping schema.sql for review',
  ],
  lounge: [
    'pulling existing copy...',
    'restructured intro for clarity',
    'added a quickstart section',
    'doc lint pass — clean',
  ],
};

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

class TaskSpawner {
  constructor() {
    this.btn = document.getElementById('new-task-btn');
    this.modal = document.getElementById('new-task-modal');
    this.input = document.getElementById('new-task-input');
    this.cancel = document.getElementById('new-task-cancel');
    this.form = this.modal.querySelector('form');

    this.btn.addEventListener('click', () => this.open());
    this.cancel.addEventListener('click', () => this.close());
    this.modal.addEventListener('click', (e) => {
      if (e.target === this.modal) this.close();
    });
    this.form.addEventListener('submit', (e) => {
      e.preventDefault();
      const v = this.input.value.trim();
      if (!v) return;
      window.dispatchEvent(new CustomEvent('agentoffice:new-task', { detail: { prompt: v } }));
      this.input.value = '';
      this.close();
    });
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && this.modal.getAttribute('aria-hidden') === 'false') {
        this.close();
      }
    });
  }

  open() {
    this.modal.setAttribute('aria-hidden', 'false');
    setTimeout(() => this.input.focus(), 50);
  }

  close() {
    this.modal.setAttribute('aria-hidden', 'true');
  }
}

class TerminalUI {
  constructor() {
    this.panel = document.getElementById('terminal-panel');
    this.log = this.panel.querySelector('[data-bind="log"]');
    this.titleEl = this.panel.querySelector('[data-bind="roomLabel"]');
    this.input = document.getElementById('terminal-input');
    this.closeBtn = document.getElementById('terminal-close');
    this.form = this.panel.querySelector('.terminal-form');

    this.activeRoom = null;
    this.logsByRoom = new Map();
    this.fsByRoom = new Map();

    this.closeBtn.addEventListener('click', () => this.close());
    this.form.addEventListener('submit', (e) => {
      e.preventDefault();
      const v = this.input.value;
      if (!v.trim()) return;
      this.handleInput(v);
      this.input.value = '';
    });
    window.addEventListener('agentoffice:room-selected', (e) => this.open(e.detail));
  }

  open(payload) {
    this.activeRoom = payload;
    this.titleEl.textContent = `${payload.label} · ${payload.roomId}`;
    this.panel.setAttribute('aria-hidden', 'false');
    this.panel.classList.add('open');

    if (!this.logsByRoom.has(payload.roomId)) {
      this.logsByRoom.set(payload.roomId, []);
      this.fsByRoom.set(payload.roomId, { ...(MOCK_FILES_BY_TYPE[payload.roomType] ?? {}) });
      this.appendLine('agent', `[${payload.label}] session attached — ${ROOM_TYPES[payload.roomType]?.ambient ?? ''}`);
      if (payload.prompt) {
        this.appendLine('user', payload.prompt);
        this.streamAgentReply(payload);
      }
    }
    this.renderLogs();
    setTimeout(() => this.input.focus(), 50);
  }

  close() {
    this.panel.setAttribute('aria-hidden', 'true');
    this.panel.classList.remove('open');
    this.activeRoom = null;
  }

  handleInput(raw) {
    if (!this.activeRoom) return;
    if (raw.startsWith('! ')) {
      const cmd = raw.slice(2).trim();
      this.appendLine('user', raw);
      this.runShell(cmd);
    } else if (raw === '!') {
      this.appendLine('shell', "usage: ! ls   |   ! cat <file>");
    } else {
      this.appendLine('user', raw);
      this.streamAgentReply({ ...this.activeRoom, prompt: raw });
    }
  }

  runShell(cmd) {
    const fs = this.fsByRoom.get(this.activeRoom.roomId) ?? {};
    if (cmd === 'ls') {
      const files = Object.keys(fs);
      this.appendLine('shell', files.length ? files.join('\n') : '(empty workspace)');
      return;
    }
    if (cmd.startsWith('cat ')) {
      const name = cmd.slice(4).trim();
      if (fs[name] != null) {
        this.appendLine('shell', fs[name]);
      } else {
        this.appendLine('error', `cat: ${name}: no such file`);
      }
      return;
    }
    if (cmd === 'pwd') {
      this.appendLine('shell', `./workspace/${this.activeRoom.roomId}/`);
      return;
    }
    if (cmd === 'help') {
      this.appendLine('shell', 'available: ls | cat <file> | pwd | help');
      return;
    }
    this.appendLine('error', `${cmd}: command not found (try: help)`);
  }

  streamAgentReply(payload) {
    const lines = MOCK_AGENT_LINES[payload.roomType] ?? MOCK_AGENT_LINES.forge;
    const line = pickRandom(lines);
    const el = document.createElement('span');
    el.className = 'line line-agent';
    el.textContent = '· ';
    this.log.appendChild(el);
    let i = 0;
    const tick = () => {
      if (i >= line.length) { this.scrollLog(); return; }
      el.textContent = '· ' + line.slice(0, ++i);
      this.scrollLog();
      setTimeout(tick, 14);
    };
    tick();
  }

  appendLine(kind, text) {
    const log = this.logsByRoom.get(this.activeRoom.roomId);
    log.push({ kind, text });
    const el = document.createElement('span');
    el.className = `line line-${kind}`;
    el.textContent =
      kind === 'user'  ? `> ${text}` :
      kind === 'agent' ? `· ${text}` :
      text;
    this.log.appendChild(el);
    this.scrollLog();
    return el;
  }

  renderLogs() {
    this.log.innerHTML = '';
    const log = this.logsByRoom.get(this.activeRoom.roomId) ?? [];
    for (const entry of log) {
      const el = document.createElement('span');
      el.className = `line line-${entry.kind}`;
      el.textContent =
        entry.kind === 'user'  ? `> ${entry.text}` :
        entry.kind === 'agent' ? `· ${entry.text}` :
        entry.text;
      this.log.appendChild(el);
    }
    this.scrollLog();
  }

  scrollLog() {
    this.log.scrollTop = this.log.scrollHeight;
  }
}

function gatePhaserKeyboard() {
  const game = window.__agentoffice?.game;
  if (!game?.input?.keyboard) return;
  const el = document.activeElement;
  const typing =
    !!el &&
    (el.tagName === 'INPUT' ||
      el.tagName === 'TEXTAREA' ||
      el.isContentEditable);
  game.input.keyboard.enabled = !typing;
}

export function initUI() {
  new TaskSpawner();
  new TerminalUI();
  document.addEventListener('focusin', gatePhaserKeyboard);
  document.addEventListener('focusout', gatePhaserKeyboard);
}
